# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

_common: !include "../hpack/common.yaml"

name: NaCl
<<: *version
synopsis: Easy-and-safe-to-use high-level Haskell bindings to NaCl
description: |
  This library uses <https://libsodium.org Sodium> under the hood,
  but only exposes the primitives that are part of the “classic” NaCl
  interface. We believe, it is better to be paranoid than sorry.

  __Note: this package is experimental and WIP.__

  Sodium is more portable, but some people prefer to stick to NaCl.
  We agree that it is better to be paranoid than sorry.
  That is why, even though this library uses
  Sodium under the hood, it only exposes the primitives that
  are part of the “classic” NaCl interface.

  Sodium provides useful algorithms, that are not part of NaCl,
  for example key derivation or random number generation.
  If you need them too (you probably do), you should use
  </package/crypto-sodium crypto-sodium> instead.

  = Secret-key cryptography

    * Authenticated encryption: "Crypto.Secretbox"

  = Public-key cryptography

    * Authenticated encryption: "Crypto.Box"
# Note: please, keep the lists above in sync with the one in crypto-sodium.

category: Cryptography

<<: *author

extra-doc-files:
  - CHANGELOG.md
  - README.md

<<: *defaults

library:
  source-dirs: lib

  dependencies: []

tests:
  test:
    <<: *test

    dependencies:
      - NaCl

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

    build-tools:
      - tasty-discover:tasty-discover
